version: '3.4'

services:
  trafficlaws-server:
    image: trafficlaws-server
    ports:
      - "3000:3000"
    working_dir: /app
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
      - '/app/node_modules'
    command: node index.js
